from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, delete
from uuid import UUID
from collections import Counter

from database import get_db
from models.scenario import Scenario
from models.policy import Policy
from schemas.scenario import ScenarioRead, ScenarioCreate, GenerationResponse
from services.scenario_generator import generate_scenarios

router = APIRouter(prefix="/scenarios", tags=["scenarios"])


@router.post("/generate/{policy_id}", response_model=GenerationResponse, status_code=201)
async def run_generation(
    policy_id: UUID,
    actor: str = "system",
    db: AsyncSession = Depends(get_db),
):
    """
    Generate scenarios from approved rules.
    Requires all rules approved and no open ambiguity flags.
    """
    try:
        scenarios = await generate_scenarios(db, str(policy_id), actor=actor)
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))

    by_type = dict(Counter(s.scenario_type for s in scenarios))
    return GenerationResponse(
        policy_id=policy_id,
        scenarios_created=len(scenarios),
        by_type=by_type,
        message=f"Generated {len(scenarios)} scenarios: {by_type}. Ready to connect your agent.",
    )


@router.get("/policy/{policy_id}", response_model=list[ScenarioRead])
async def list_scenarios(
    policy_id: UUID,
    scenario_type: str | None = None,
    risk_tier: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    """List scenarios for a policy with optional filters."""
    query = select(Scenario).where(Scenario.policy_id == policy_id)
    if scenario_type:
        query = query.where(Scenario.scenario_type == scenario_type)
    if risk_tier:
        query = query.where(Scenario.risk_tier == risk_tier)
    query = query.order_by(Scenario.scenario_number)
    result = await db.execute(query)
    return result.scalars().all()


@router.get("/{scenario_id}", response_model=ScenarioRead)
async def get_scenario(scenario_id: UUID, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Scenario).where(Scenario.id == scenario_id))
    s = result.scalar_one_or_none()
    if not s:
        raise HTTPException(status_code=404, detail="Scenario not found.")
    return s


@router.post("/policy/{policy_id}/custom", response_model=ScenarioRead, status_code=201)
async def add_custom_scenario(
    policy_id: UUID,
    payload: ScenarioCreate,
    db: AsyncSession = Depends(get_db),
):
    """Add a custom scenario not generated by Claude (e.g. from a real incident)."""
    pol = await db.get(Policy, policy_id)
    if not pol:
        raise HTTPException(status_code=404, detail="Policy not found.")

    count_result = await db.execute(
        select(Scenario).where(Scenario.policy_id == policy_id)
    )
    existing = count_result.scalars().all()
    next_num = f"S{len(existing) + 1}"

    scenario = Scenario(
        policy_id=policy_id,
        scenario_number=next_num,
        is_custom=True,
        **payload.model_dump(),
    )
    db.add(scenario)
    await db.flush()
    return scenario


@router.delete("/policy/{policy_id}", status_code=204)
async def delete_all_scenarios(policy_id: UUID, db: AsyncSession = Depends(get_db)):
    """Delete all scenarios for a policy so they can be regenerated."""
    await db.execute(delete(Scenario).where(Scenario.policy_id == policy_id))
