from pydantic import BaseModel, field_validator
from datetime import datetime
from uuid import UUID
from typing import Literal, Any


ScenarioType = Literal["normal", "edge", "exception", "adversarial"]
RiskTier = Literal["critical", "standard", "low"]


class ScenarioRead(BaseModel):
    id: UUID
    policy_id: UUID
    scenario_number: str
    title: str
    customer_message: str
    scenario_type: str
    rule_ids_tested: list[str] = []
    expected_action: str

    @field_validator("rule_ids_tested", mode="before")
    @classmethod
    def coerce_uuids_to_str(cls, v: Any) -> list[str]:
        if not v:
            return []
        return [str(item) for item in v]
    expected_explanation: str
    risk_tier: str
    is_custom: bool
    created_at: datetime

    model_config = {"from_attributes": True}


class ScenarioCreate(BaseModel):
    """For manually adding a scenario not generated by Claude."""
    title: str
    customer_message: str
    scenario_type: ScenarioType
    rule_ids_tested: list[str] = []
    expected_action: str
    expected_explanation: str
    risk_tier: RiskTier = "standard"


class GenerationResponse(BaseModel):
    policy_id: UUID
    scenarios_created: int
    by_type: dict[str, int]
    message: str
